# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-25 11:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acknowledges',
            fields=[
                ('acknowledgeid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('clock', models.IntegerField()),
                ('message', models.CharField(max_length=255)),
                ('action', models.IntegerField()),
            ],
            options={
                'db_table': 'acknowledges',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Actions',
            fields=[
                ('actionid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('eventsource', models.IntegerField()),
                ('evaltype', models.IntegerField()),
                ('status', models.IntegerField()),
                ('esc_period', models.CharField(max_length=255)),
                ('def_shortdata', models.CharField(max_length=255)),
                ('def_longdata', models.TextField()),
                ('r_shortdata', models.CharField(max_length=255)),
                ('r_longdata', models.TextField()),
                ('formula', models.CharField(max_length=255)),
                ('maintenance_mode', models.IntegerField()),
                ('ack_shortdata', models.CharField(max_length=255)),
                ('ack_longdata', models.TextField()),
            ],
            options={
                'db_table': 'actions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Alerts',
            fields=[
                ('alertid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('clock', models.IntegerField()),
                ('sendto', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('status', models.IntegerField()),
                ('retries', models.IntegerField()),
                ('error', models.CharField(max_length=2048)),
                ('esc_step', models.IntegerField()),
                ('alerttype', models.IntegerField()),
            ],
            options={
                'db_table': 'alerts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ApplicationDiscovery',
            fields=[
                ('application_discoveryid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('lastcheck', models.IntegerField()),
                ('ts_delete', models.IntegerField()),
            ],
            options={
                'db_table': 'application_discovery',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ApplicationPrototype',
            fields=[
                ('application_prototypeid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'application_prototype',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('applicationid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('flags', models.IntegerField()),
            ],
            options={
                'db_table': 'applications',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ApplicationTemplate',
            fields=[
                ('application_templateid', models.BigIntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'application_template',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Auditlog',
            fields=[
                ('auditid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('clock', models.IntegerField()),
                ('action', models.IntegerField()),
                ('resourcetype', models.IntegerField()),
                ('details', models.CharField(max_length=128)),
                ('ip', models.CharField(max_length=39)),
                ('resourceid', models.BigIntegerField()),
                ('resourcename', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'auditlog',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuditlogDetails',
            fields=[
                ('auditdetailid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('table_name', models.CharField(max_length=64)),
                ('field_name', models.CharField(max_length=64)),
                ('oldvalue', models.TextField()),
                ('newvalue', models.TextField()),
            ],
            options={
                'db_table': 'auditlog_details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AutoregHost',
            fields=[
                ('autoreg_hostid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('host', models.CharField(max_length=64)),
                ('listen_ip', models.CharField(max_length=39)),
                ('listen_port', models.IntegerField()),
                ('listen_dns', models.CharField(max_length=64)),
                ('host_metadata', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'autoreg_host',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Conditions',
            fields=[
                ('conditionid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('conditiontype', models.IntegerField()),
                ('operator', models.IntegerField()),
                ('value', models.CharField(max_length=255)),
                ('value2', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'conditions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Config',
            fields=[
                ('configid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('refresh_unsupported', models.CharField(max_length=32)),
                ('work_period', models.CharField(max_length=255)),
                ('event_ack_enable', models.IntegerField()),
                ('event_expire', models.CharField(max_length=32)),
                ('event_show_max', models.IntegerField()),
                ('default_theme', models.CharField(max_length=128)),
                ('authentication_type', models.IntegerField()),
                ('ldap_host', models.CharField(max_length=255)),
                ('ldap_port', models.IntegerField()),
                ('ldap_base_dn', models.CharField(max_length=255)),
                ('ldap_bind_dn', models.CharField(max_length=255)),
                ('ldap_bind_password', models.CharField(max_length=128)),
                ('ldap_search_attribute', models.CharField(max_length=128)),
                ('dropdown_first_entry', models.IntegerField()),
                ('dropdown_first_remember', models.IntegerField()),
                ('max_in_table', models.IntegerField()),
                ('search_limit', models.IntegerField()),
                ('severity_color_0', models.CharField(max_length=6)),
                ('severity_color_1', models.CharField(max_length=6)),
                ('severity_color_2', models.CharField(max_length=6)),
                ('severity_color_3', models.CharField(max_length=6)),
                ('severity_color_4', models.CharField(max_length=6)),
                ('severity_color_5', models.CharField(max_length=6)),
                ('severity_name_0', models.CharField(max_length=32)),
                ('severity_name_1', models.CharField(max_length=32)),
                ('severity_name_2', models.CharField(max_length=32)),
                ('severity_name_3', models.CharField(max_length=32)),
                ('severity_name_4', models.CharField(max_length=32)),
                ('severity_name_5', models.CharField(max_length=32)),
                ('ok_period', models.CharField(max_length=32)),
                ('blink_period', models.CharField(max_length=32)),
                ('problem_unack_color', models.CharField(max_length=6)),
                ('problem_ack_color', models.CharField(max_length=6)),
                ('ok_unack_color', models.CharField(max_length=6)),
                ('ok_ack_color', models.CharField(max_length=6)),
                ('problem_unack_style', models.IntegerField()),
                ('problem_ack_style', models.IntegerField()),
                ('ok_unack_style', models.IntegerField()),
                ('ok_ack_style', models.IntegerField()),
                ('snmptrap_logging', models.IntegerField()),
                ('server_check_interval', models.IntegerField()),
                ('hk_events_mode', models.IntegerField()),
                ('hk_events_trigger', models.CharField(max_length=32)),
                ('hk_events_internal', models.CharField(max_length=32)),
                ('hk_events_discovery', models.CharField(max_length=32)),
                ('hk_events_autoreg', models.CharField(max_length=32)),
                ('hk_services_mode', models.IntegerField()),
                ('hk_services', models.CharField(max_length=32)),
                ('hk_audit_mode', models.IntegerField()),
                ('hk_audit', models.CharField(max_length=32)),
                ('hk_sessions_mode', models.IntegerField()),
                ('hk_sessions', models.CharField(max_length=32)),
                ('hk_history_mode', models.IntegerField()),
                ('hk_history_global', models.IntegerField()),
                ('hk_history', models.CharField(max_length=32)),
                ('hk_trends_mode', models.IntegerField()),
                ('hk_trends_global', models.IntegerField()),
                ('hk_trends', models.CharField(max_length=32)),
                ('default_inventory_mode', models.IntegerField()),
            ],
            options={
                'db_table': 'config',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CorrCondition',
            fields=[
                ('corr_conditionid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('type', models.IntegerField()),
            ],
            options={
                'db_table': 'corr_condition',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Correlation',
            fields=[
                ('correlationid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('evaltype', models.IntegerField()),
                ('status', models.IntegerField()),
                ('formula', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'correlation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CorrOperation',
            fields=[
                ('corr_operationid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('type', models.IntegerField()),
            ],
            options={
                'db_table': 'corr_operation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('dashboardid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('private', models.IntegerField()),
            ],
            options={
                'db_table': 'dashboard',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DashboardUser',
            fields=[
                ('dashboard_userid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('permission', models.IntegerField()),
            ],
            options={
                'db_table': 'dashboard_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DashboardUsrgrp',
            fields=[
                ('dashboard_usrgrpid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('permission', models.IntegerField()),
            ],
            options={
                'db_table': 'dashboard_usrgrp',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Dbversion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mandatory', models.IntegerField()),
                ('optional', models.IntegerField()),
            ],
            options={
                'db_table': 'dbversion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Dchecks',
            fields=[
                ('dcheckid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('type', models.IntegerField()),
                ('key_field', models.CharField(db_column='key_', max_length=512)),
                ('snmp_community', models.CharField(max_length=255)),
                ('ports', models.CharField(max_length=255)),
                ('snmpv3_securityname', models.CharField(max_length=64)),
                ('snmpv3_securitylevel', models.IntegerField()),
                ('snmpv3_authpassphrase', models.CharField(max_length=64)),
                ('snmpv3_privpassphrase', models.CharField(max_length=64)),
                ('uniq', models.IntegerField()),
                ('snmpv3_authprotocol', models.IntegerField()),
                ('snmpv3_privprotocol', models.IntegerField()),
                ('snmpv3_contextname', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'dchecks',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Dhosts',
            fields=[
                ('dhostid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('status', models.IntegerField()),
                ('lastup', models.IntegerField()),
                ('lastdown', models.IntegerField()),
            ],
            options={
                'db_table': 'dhosts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Drules',
            fields=[
                ('druleid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('iprange', models.CharField(max_length=2048)),
                ('delay', models.CharField(max_length=255)),
                ('nextcheck', models.IntegerField()),
                ('status', models.IntegerField()),
            ],
            options={
                'db_table': 'drules',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Dservices',
            fields=[
                ('dserviceid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=255)),
                ('port', models.IntegerField()),
                ('status', models.IntegerField()),
                ('lastup', models.IntegerField()),
                ('lastdown', models.IntegerField()),
                ('ip', models.CharField(max_length=39)),
                ('dns', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'dservices',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Escalations',
            fields=[
                ('escalationid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('actionid', models.BigIntegerField()),
                ('triggerid', models.BigIntegerField(blank=True, null=True)),
                ('eventid', models.BigIntegerField(blank=True, null=True)),
                ('r_eventid', models.BigIntegerField(blank=True, null=True)),
                ('nextcheck', models.IntegerField()),
                ('esc_step', models.IntegerField()),
                ('status', models.IntegerField()),
                ('itemid', models.BigIntegerField(blank=True, null=True)),
                ('acknowledgeid', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'escalations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('eventid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('source', models.IntegerField()),
                ('object', models.IntegerField()),
                ('objectid', models.BigIntegerField()),
                ('clock', models.IntegerField()),
                ('value', models.IntegerField()),
                ('acknowledged', models.IntegerField()),
                ('ns', models.IntegerField()),
            ],
            options={
                'db_table': 'events',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EventTag',
            fields=[
                ('eventtagid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('tag', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'event_tag',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Expressions',
            fields=[
                ('expressionid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('expression', models.CharField(max_length=255)),
                ('expression_type', models.IntegerField()),
                ('exp_delimiter', models.CharField(max_length=1)),
                ('case_sensitive', models.IntegerField()),
            ],
            options={
                'db_table': 'expressions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Functions',
            fields=[
                ('functionid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('function', models.CharField(max_length=12)),
                ('parameter', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'functions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Globalmacro',
            fields=[
                ('globalmacroid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('macro', models.CharField(max_length=255, unique=True)),
                ('value', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'globalmacro',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Globalvars',
            fields=[
                ('globalvarid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('snmp_lastsize', models.BigIntegerField()),
            ],
            options={
                'db_table': 'globalvars',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Graphs',
            fields=[
                ('graphid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('yaxismin', models.FloatField()),
                ('yaxismax', models.FloatField()),
                ('show_work_period', models.IntegerField()),
                ('show_triggers', models.IntegerField()),
                ('graphtype', models.IntegerField()),
                ('show_legend', models.IntegerField()),
                ('show_3d', models.IntegerField()),
                ('percent_left', models.FloatField()),
                ('percent_right', models.FloatField()),
                ('ymin_type', models.IntegerField()),
                ('ymax_type', models.IntegerField()),
                ('flags', models.IntegerField()),
            ],
            options={
                'db_table': 'graphs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GraphsItems',
            fields=[
                ('gitemid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('drawtype', models.IntegerField()),
                ('sortorder', models.IntegerField()),
                ('color', models.CharField(max_length=6)),
                ('yaxisside', models.IntegerField()),
                ('calc_fnc', models.IntegerField()),
                ('type', models.IntegerField()),
            ],
            options={
                'db_table': 'graphs_items',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GraphTheme',
            fields=[
                ('graphthemeid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('theme', models.CharField(max_length=64, unique=True)),
                ('backgroundcolor', models.CharField(max_length=6)),
                ('graphcolor', models.CharField(max_length=6)),
                ('gridcolor', models.CharField(max_length=6)),
                ('maingridcolor', models.CharField(max_length=6)),
                ('gridbordercolor', models.CharField(max_length=6)),
                ('textcolor', models.CharField(max_length=6)),
                ('highlightcolor', models.CharField(max_length=6)),
                ('leftpercentilecolor', models.CharField(max_length=6)),
                ('rightpercentilecolor', models.CharField(max_length=6)),
                ('nonworktimecolor', models.CharField(max_length=6)),
            ],
            options={
                'db_table': 'graph_theme',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GroupPrototype',
            fields=[
                ('group_prototypeid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'group_prototype',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('groupid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('internal', models.IntegerField()),
                ('flags', models.IntegerField()),
            ],
            options={
                'db_table': 'groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemid', models.BigIntegerField()),
                ('clock', models.IntegerField()),
                ('value', models.FloatField()),
                ('ns', models.IntegerField()),
            ],
            options={
                'db_table': 'history',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HistoryLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemid', models.BigIntegerField()),
                ('clock', models.IntegerField()),
                ('timestamp', models.IntegerField()),
                ('source', models.CharField(max_length=64)),
                ('severity', models.IntegerField()),
                ('value', models.TextField()),
                ('logeventid', models.IntegerField()),
                ('ns', models.IntegerField()),
            ],
            options={
                'db_table': 'history_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HistoryStr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemid', models.BigIntegerField()),
                ('clock', models.IntegerField()),
                ('value', models.CharField(max_length=255)),
                ('ns', models.IntegerField()),
            ],
            options={
                'db_table': 'history_str',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HistoryText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemid', models.BigIntegerField()),
                ('clock', models.IntegerField()),
                ('value', models.TextField()),
                ('ns', models.IntegerField()),
            ],
            options={
                'db_table': 'history_text',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HistoryUint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemid', models.BigIntegerField()),
                ('clock', models.IntegerField()),
                ('value', models.BigIntegerField()),
                ('ns', models.IntegerField()),
            ],
            options={
                'db_table': 'history_uint',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Hostmacro',
            fields=[
                ('hostmacroid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('macro', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'hostmacro',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Hosts',
            fields=[
                ('hostid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('host', models.CharField(max_length=128)),
                ('status', models.IntegerField()),
                ('disable_until', models.IntegerField()),
                ('error', models.CharField(max_length=2048)),
                ('available', models.IntegerField()),
                ('errors_from', models.IntegerField()),
                ('lastaccess', models.IntegerField()),
                ('ipmi_authtype', models.IntegerField()),
                ('ipmi_privilege', models.IntegerField()),
                ('ipmi_username', models.CharField(max_length=16)),
                ('ipmi_password', models.CharField(max_length=20)),
                ('ipmi_disable_until', models.IntegerField()),
                ('ipmi_available', models.IntegerField()),
                ('snmp_disable_until', models.IntegerField()),
                ('snmp_available', models.IntegerField()),
                ('maintenance_status', models.IntegerField()),
                ('maintenance_type', models.IntegerField()),
                ('maintenance_from', models.IntegerField()),
                ('ipmi_errors_from', models.IntegerField()),
                ('snmp_errors_from', models.IntegerField()),
                ('ipmi_error', models.CharField(max_length=2048)),
                ('snmp_error', models.CharField(max_length=2048)),
                ('jmx_disable_until', models.IntegerField()),
                ('jmx_available', models.IntegerField()),
                ('jmx_errors_from', models.IntegerField()),
                ('jmx_error', models.CharField(max_length=2048)),
                ('name', models.CharField(max_length=128)),
                ('flags', models.IntegerField()),
                ('description', models.TextField()),
                ('tls_connect', models.IntegerField()),
                ('tls_accept', models.IntegerField()),
                ('tls_issuer', models.CharField(max_length=1024)),
                ('tls_subject', models.CharField(max_length=1024)),
                ('tls_psk_identity', models.CharField(max_length=128)),
                ('tls_psk', models.CharField(max_length=512)),
            ],
            options={
                'db_table': 'hosts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HostsGroups',
            fields=[
                ('hostgroupid', models.BigIntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'hosts_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HostsTemplates',
            fields=[
                ('hosttemplateid', models.BigIntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'hosts_templates',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Housekeeper',
            fields=[
                ('housekeeperid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('tablename', models.CharField(max_length=64)),
                ('field', models.CharField(max_length=64)),
                ('value', models.BigIntegerField()),
            ],
            options={
                'db_table': 'housekeeper',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Httpstep',
            fields=[
                ('httpstepid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('no', models.IntegerField()),
                ('url', models.CharField(max_length=2048)),
                ('timeout', models.CharField(max_length=255)),
                ('posts', models.TextField()),
                ('required', models.CharField(max_length=255)),
                ('status_codes', models.CharField(max_length=255)),
                ('follow_redirects', models.IntegerField()),
                ('retrieve_mode', models.IntegerField()),
                ('post_type', models.IntegerField()),
            ],
            options={
                'db_table': 'httpstep',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HttpstepField',
            fields=[
                ('httpstep_fieldid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('type', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('value', models.TextField()),
            ],
            options={
                'db_table': 'httpstep_field',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Httpstepitem',
            fields=[
                ('httpstepitemid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('type', models.IntegerField()),
            ],
            options={
                'db_table': 'httpstepitem',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Httptest',
            fields=[
                ('httptestid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('nextcheck', models.IntegerField()),
                ('delay', models.CharField(max_length=255)),
                ('status', models.IntegerField()),
                ('agent', models.CharField(max_length=255)),
                ('authentication', models.IntegerField()),
                ('http_user', models.CharField(max_length=64)),
                ('http_password', models.CharField(max_length=64)),
                ('http_proxy', models.CharField(max_length=255)),
                ('retries', models.IntegerField()),
                ('ssl_cert_file', models.CharField(max_length=255)),
                ('ssl_key_file', models.CharField(max_length=255)),
                ('ssl_key_password', models.CharField(max_length=64)),
                ('verify_peer', models.IntegerField()),
                ('verify_host', models.IntegerField()),
            ],
            options={
                'db_table': 'httptest',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HttptestField',
            fields=[
                ('httptest_fieldid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('type', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('value', models.TextField()),
            ],
            options={
                'db_table': 'httptest_field',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Httptestitem',
            fields=[
                ('httptestitemid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('type', models.IntegerField()),
            ],
            options={
                'db_table': 'httptestitem',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IconMap',
            fields=[
                ('iconmapid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'db_table': 'icon_map',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IconMapping',
            fields=[
                ('iconmappingid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('inventory_link', models.IntegerField()),
                ('expression', models.CharField(max_length=64)),
                ('sortorder', models.IntegerField()),
            ],
            options={
                'db_table': 'icon_mapping',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ids',
            fields=[
                ('table_name', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('field_name', models.CharField(max_length=64)),
                ('nextid', models.BigIntegerField()),
            ],
            options={
                'db_table': 'ids',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('imageid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('imagetype', models.IntegerField()),
                ('name', models.CharField(max_length=64, unique=True)),
                ('image', models.TextField()),
            ],
            options={
                'db_table': 'images',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Interface',
            fields=[
                ('interfaceid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('main', models.IntegerField()),
                ('type', models.IntegerField()),
                ('useip', models.IntegerField()),
                ('ip', models.CharField(max_length=64)),
                ('dns', models.CharField(max_length=64)),
                ('port', models.CharField(max_length=64)),
                ('bulk', models.IntegerField()),
            ],
            options={
                'db_table': 'interface',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ItemApplicationPrototype',
            fields=[
                ('item_application_prototypeid', models.BigIntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'item_application_prototype',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ItemCondition',
            fields=[
                ('item_conditionid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('operator', models.IntegerField()),
                ('macro', models.CharField(max_length=64)),
                ('value', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'item_condition',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ItemDiscovery',
            fields=[
                ('itemdiscoveryid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('key_field', models.CharField(db_column='key_', max_length=255)),
                ('lastcheck', models.IntegerField()),
                ('ts_delete', models.IntegerField()),
            ],
            options={
                'db_table': 'item_discovery',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ItemLastvalue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemid', models.BigIntegerField(unique=True)),
                ('clock', models.IntegerField()),
                ('value', models.TextField()),
                ('ns', models.IntegerField()),
            ],
            options={
                'db_table': 'item_lastvalue',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ItemPreproc',
            fields=[
                ('item_preprocid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('step', models.IntegerField()),
                ('type', models.IntegerField()),
                ('params', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'item_preproc',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('itemid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('type', models.IntegerField()),
                ('snmp_community', models.CharField(max_length=64)),
                ('snmp_oid', models.CharField(max_length=512)),
                ('name', models.CharField(max_length=255)),
                ('key_field', models.CharField(db_column='key_', max_length=255)),
                ('delay', models.CharField(max_length=1024)),
                ('history', models.CharField(max_length=255)),
                ('trends', models.CharField(max_length=255)),
                ('status', models.IntegerField()),
                ('value_type', models.IntegerField()),
                ('trapper_hosts', models.CharField(max_length=255)),
                ('units', models.CharField(max_length=255)),
                ('snmpv3_securityname', models.CharField(max_length=64)),
                ('snmpv3_securitylevel', models.IntegerField()),
                ('snmpv3_authpassphrase', models.CharField(max_length=64)),
                ('snmpv3_privpassphrase', models.CharField(max_length=64)),
                ('formula', models.CharField(max_length=255)),
                ('error', models.CharField(max_length=2048)),
                ('lastlogsize', models.BigIntegerField()),
                ('logtimefmt', models.CharField(max_length=64)),
                ('params', models.TextField()),
                ('ipmi_sensor', models.CharField(max_length=128)),
                ('authtype', models.IntegerField()),
                ('username', models.CharField(max_length=64)),
                ('password', models.CharField(max_length=64)),
                ('publickey', models.CharField(max_length=64)),
                ('privatekey', models.CharField(max_length=64)),
                ('mtime', models.IntegerField()),
                ('flags', models.IntegerField()),
                ('port', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('inventory_link', models.IntegerField()),
                ('lifetime', models.CharField(max_length=255)),
                ('snmpv3_authprotocol', models.IntegerField()),
                ('snmpv3_privprotocol', models.IntegerField()),
                ('state', models.IntegerField()),
                ('snmpv3_contextname', models.CharField(max_length=255)),
                ('evaltype', models.IntegerField()),
                ('jmx_endpoint', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'items',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ItemsApplications',
            fields=[
                ('itemappid', models.BigIntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'items_applications',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Maintenances',
            fields=[
                ('maintenanceid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('maintenance_type', models.IntegerField()),
                ('description', models.TextField()),
                ('active_since', models.IntegerField()),
                ('active_till', models.IntegerField()),
            ],
            options={
                'db_table': 'maintenances',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MaintenancesGroups',
            fields=[
                ('maintenance_groupid', models.BigIntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'maintenances_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MaintenancesHosts',
            fields=[
                ('maintenance_hostid', models.BigIntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'maintenances_hosts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MaintenancesWindows',
            fields=[
                ('maintenance_timeperiodid', models.BigIntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'maintenances_windows',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mappings',
            fields=[
                ('mappingid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=64)),
                ('newvalue', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'mappings',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('mediaid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('sendto', models.CharField(max_length=100)),
                ('active', models.IntegerField()),
                ('severity', models.IntegerField()),
                ('period', models.CharField(max_length=1024)),
            ],
            options={
                'db_table': 'media',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MediaType',
            fields=[
                ('mediatypeid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('type', models.IntegerField()),
                ('description', models.CharField(max_length=100, unique=True)),
                ('smtp_server', models.CharField(max_length=255)),
                ('smtp_helo', models.CharField(max_length=255)),
                ('smtp_email', models.CharField(max_length=255)),
                ('exec_path', models.CharField(max_length=255)),
                ('gsm_modem', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('passwd', models.CharField(max_length=255)),
                ('status', models.IntegerField()),
                ('smtp_port', models.IntegerField()),
                ('smtp_security', models.IntegerField()),
                ('smtp_verify_peer', models.IntegerField()),
                ('smtp_verify_host', models.IntegerField()),
                ('smtp_authentication', models.IntegerField()),
                ('exec_params', models.CharField(max_length=255)),
                ('maxsessions', models.IntegerField()),
                ('maxattempts', models.IntegerField()),
                ('attempt_interval', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'media_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OpcommandGrp',
            fields=[
                ('opcommand_grpid', models.BigIntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'opcommand_grp',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OpcommandHst',
            fields=[
                ('opcommand_hstid', models.BigIntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'opcommand_hst',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Opconditions',
            fields=[
                ('opconditionid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('conditiontype', models.IntegerField()),
                ('operator', models.IntegerField()),
                ('value', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'opconditions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Operations',
            fields=[
                ('operationid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('operationtype', models.IntegerField()),
                ('esc_period', models.CharField(max_length=255)),
                ('esc_step_from', models.IntegerField()),
                ('esc_step_to', models.IntegerField()),
                ('evaltype', models.IntegerField()),
                ('recovery', models.IntegerField()),
            ],
            options={
                'db_table': 'operations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Opgroup',
            fields=[
                ('opgroupid', models.BigIntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'opgroup',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OpmessageGrp',
            fields=[
                ('opmessage_grpid', models.BigIntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'opmessage_grp',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OpmessageUsr',
            fields=[
                ('opmessage_usrid', models.BigIntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'opmessage_usr',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Optemplate',
            fields=[
                ('optemplateid', models.BigIntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'optemplate',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProblemTag',
            fields=[
                ('problemtagid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('tag', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'problem_tag',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Profiles',
            fields=[
                ('profileid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('idx', models.CharField(max_length=96)),
                ('idx2', models.BigIntegerField()),
                ('value_id', models.BigIntegerField()),
                ('value_int', models.IntegerField()),
                ('value_str', models.CharField(max_length=255)),
                ('source', models.CharField(max_length=96)),
                ('type', models.IntegerField()),
            ],
            options={
                'db_table': 'profiles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProxyAutoregHost',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('clock', models.IntegerField()),
                ('host', models.CharField(max_length=64)),
                ('listen_ip', models.CharField(max_length=39)),
                ('listen_port', models.IntegerField()),
                ('listen_dns', models.CharField(max_length=64)),
                ('host_metadata', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'proxy_autoreg_host',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProxyDhistory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('clock', models.IntegerField()),
                ('druleid', models.BigIntegerField()),
                ('ip', models.CharField(max_length=39)),
                ('port', models.IntegerField()),
                ('value', models.CharField(max_length=255)),
                ('status', models.IntegerField()),
                ('dcheckid', models.BigIntegerField(blank=True, null=True)),
                ('dns', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'proxy_dhistory',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProxyHistory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('itemid', models.BigIntegerField()),
                ('clock', models.IntegerField()),
                ('timestamp', models.IntegerField()),
                ('source', models.CharField(max_length=64)),
                ('severity', models.IntegerField()),
                ('value', models.TextField()),
                ('logeventid', models.IntegerField()),
                ('ns', models.IntegerField()),
                ('state', models.IntegerField()),
                ('lastlogsize', models.BigIntegerField()),
                ('mtime', models.IntegerField()),
                ('flags', models.IntegerField()),
            ],
            options={
                'db_table': 'proxy_history',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Regexps',
            fields=[
                ('regexpid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('test_string', models.TextField()),
            ],
            options={
                'db_table': 'regexps',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rights',
            fields=[
                ('rightid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('permission', models.IntegerField()),
            ],
            options={
                'db_table': 'rights',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Screens',
            fields=[
                ('screenid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('hsize', models.IntegerField()),
                ('vsize', models.IntegerField()),
                ('private', models.IntegerField()),
            ],
            options={
                'db_table': 'screens',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ScreensItems',
            fields=[
                ('screenitemid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('resourcetype', models.IntegerField()),
                ('resourceid', models.BigIntegerField()),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('colspan', models.IntegerField()),
                ('rowspan', models.IntegerField()),
                ('elements', models.IntegerField()),
                ('valign', models.IntegerField()),
                ('halign', models.IntegerField()),
                ('style', models.IntegerField()),
                ('url', models.CharField(max_length=255)),
                ('dynamic', models.IntegerField()),
                ('sort_triggers', models.IntegerField()),
                ('application', models.CharField(max_length=255)),
                ('max_columns', models.IntegerField()),
            ],
            options={
                'db_table': 'screens_items',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ScreenUser',
            fields=[
                ('screenuserid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('permission', models.IntegerField()),
            ],
            options={
                'db_table': 'screen_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ScreenUsrgrp',
            fields=[
                ('screenusrgrpid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('permission', models.IntegerField()),
            ],
            options={
                'db_table': 'screen_usrgrp',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Scripts',
            fields=[
                ('scriptid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('command', models.CharField(max_length=255)),
                ('host_access', models.IntegerField()),
                ('description', models.TextField()),
                ('confirmation', models.CharField(max_length=255)),
                ('type', models.IntegerField()),
                ('execute_on', models.IntegerField()),
            ],
            options={
                'db_table': 'scripts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ServiceAlarms',
            fields=[
                ('servicealarmid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('clock', models.IntegerField()),
                ('value', models.IntegerField()),
            ],
            options={
                'db_table': 'service_alarms',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('serviceid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('status', models.IntegerField()),
                ('algorithm', models.IntegerField()),
                ('showsla', models.IntegerField()),
                ('goodsla', models.FloatField()),
                ('sortorder', models.IntegerField()),
            ],
            options={
                'db_table': 'services',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ServicesLinks',
            fields=[
                ('linkid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('soft', models.IntegerField()),
            ],
            options={
                'db_table': 'services_links',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ServicesTimes',
            fields=[
                ('timeid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('type', models.IntegerField()),
                ('ts_from', models.IntegerField()),
                ('ts_to', models.IntegerField()),
                ('note', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'services_times',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sessions',
            fields=[
                ('sessionid', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('lastaccess', models.IntegerField()),
                ('status', models.IntegerField()),
            ],
            options={
                'db_table': 'sessions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Slides',
            fields=[
                ('slideid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('step', models.IntegerField()),
                ('delay', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'slides',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Slideshows',
            fields=[
                ('slideshowid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('delay', models.CharField(max_length=32)),
                ('private', models.IntegerField()),
            ],
            options={
                'db_table': 'slideshows',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SlideshowUser',
            fields=[
                ('slideshowuserid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('permission', models.IntegerField()),
            ],
            options={
                'db_table': 'slideshow_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SlideshowUsrgrp',
            fields=[
                ('slideshowusrgrpid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('permission', models.IntegerField()),
            ],
            options={
                'db_table': 'slideshow_usrgrp',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SysmapElementTrigger',
            fields=[
                ('selement_triggerid', models.BigIntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'sysmap_element_trigger',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SysmapElementUrl',
            fields=[
                ('sysmapelementurlid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'sysmap_element_url',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sysmaps',
            fields=[
                ('sysmapid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('label_type', models.IntegerField()),
                ('label_location', models.IntegerField()),
                ('highlight', models.IntegerField()),
                ('expandproblem', models.IntegerField()),
                ('markelements', models.IntegerField()),
                ('show_unack', models.IntegerField()),
                ('grid_size', models.IntegerField()),
                ('grid_show', models.IntegerField()),
                ('grid_align', models.IntegerField()),
                ('label_format', models.IntegerField()),
                ('label_type_host', models.IntegerField()),
                ('label_type_hostgroup', models.IntegerField()),
                ('label_type_trigger', models.IntegerField()),
                ('label_type_map', models.IntegerField()),
                ('label_type_image', models.IntegerField()),
                ('label_string_host', models.CharField(max_length=255)),
                ('label_string_hostgroup', models.CharField(max_length=255)),
                ('label_string_trigger', models.CharField(max_length=255)),
                ('label_string_map', models.CharField(max_length=255)),
                ('label_string_image', models.CharField(max_length=255)),
                ('expand_macros', models.IntegerField()),
                ('severity_min', models.IntegerField()),
                ('private', models.IntegerField()),
            ],
            options={
                'db_table': 'sysmaps',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SysmapsElements',
            fields=[
                ('selementid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('elementid', models.BigIntegerField()),
                ('elementtype', models.IntegerField()),
                ('label', models.CharField(max_length=2048)),
                ('label_location', models.IntegerField()),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('elementsubtype', models.IntegerField()),
                ('areatype', models.IntegerField()),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('viewtype', models.IntegerField()),
                ('use_iconmap', models.IntegerField()),
                ('application', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'sysmaps_elements',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SysmapShape',
            fields=[
                ('sysmap_shapeid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('type', models.IntegerField()),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('text', models.TextField()),
                ('font', models.IntegerField()),
                ('font_size', models.IntegerField()),
                ('font_color', models.CharField(max_length=6)),
                ('text_halign', models.IntegerField()),
                ('text_valign', models.IntegerField()),
                ('border_type', models.IntegerField()),
                ('border_width', models.IntegerField()),
                ('border_color', models.CharField(max_length=6)),
                ('background_color', models.CharField(max_length=6)),
                ('zindex', models.IntegerField()),
            ],
            options={
                'db_table': 'sysmap_shape',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SysmapsLinks',
            fields=[
                ('linkid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('drawtype', models.IntegerField()),
                ('color', models.CharField(max_length=6)),
                ('label', models.CharField(max_length=2048)),
            ],
            options={
                'db_table': 'sysmaps_links',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SysmapsLinkTriggers',
            fields=[
                ('linktriggerid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('drawtype', models.IntegerField()),
                ('color', models.CharField(max_length=6)),
            ],
            options={
                'db_table': 'sysmaps_link_triggers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SysmapUrl',
            fields=[
                ('sysmapurlid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('elementtype', models.IntegerField()),
            ],
            options={
                'db_table': 'sysmap_url',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SysmapUser',
            fields=[
                ('sysmapuserid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('permission', models.IntegerField()),
            ],
            options={
                'db_table': 'sysmap_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SysmapUsrgrp',
            fields=[
                ('sysmapusrgrpid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('permission', models.IntegerField()),
            ],
            options={
                'db_table': 'sysmap_usrgrp',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('taskid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('type', models.IntegerField()),
                ('status', models.IntegerField()),
                ('clock', models.IntegerField()),
                ('ttl', models.IntegerField()),
            ],
            options={
                'db_table': 'task',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Timeperiods',
            fields=[
                ('timeperiodid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('timeperiod_type', models.IntegerField()),
                ('every', models.IntegerField()),
                ('month', models.IntegerField()),
                ('dayofweek', models.IntegerField()),
                ('day', models.IntegerField()),
                ('start_time', models.IntegerField()),
                ('period', models.IntegerField()),
                ('start_date', models.IntegerField()),
            ],
            options={
                'db_table': 'timeperiods',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Trends',
            fields=[
                ('itemid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('clock', models.IntegerField()),
                ('num', models.IntegerField()),
                ('value_min', models.FloatField()),
                ('value_avg', models.FloatField()),
                ('value_max', models.FloatField()),
            ],
            options={
                'db_table': 'trends',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TrendsUint',
            fields=[
                ('itemid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('clock', models.IntegerField()),
                ('num', models.IntegerField()),
                ('value_min', models.BigIntegerField()),
                ('value_avg', models.BigIntegerField()),
                ('value_max', models.BigIntegerField()),
            ],
            options={
                'db_table': 'trends_uint',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TriggerDepends',
            fields=[
                ('triggerdepid', models.BigIntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'trigger_depends',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Triggers',
            fields=[
                ('triggerid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('expression', models.CharField(max_length=2048)),
                ('description', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('status', models.IntegerField()),
                ('value', models.IntegerField()),
                ('priority', models.IntegerField()),
                ('lastchange', models.IntegerField()),
                ('comments', models.TextField()),
                ('error', models.CharField(max_length=2048)),
                ('type', models.IntegerField()),
                ('state', models.IntegerField()),
                ('flags', models.IntegerField()),
                ('recovery_mode', models.IntegerField()),
                ('recovery_expression', models.CharField(max_length=2048)),
                ('correlation_mode', models.IntegerField()),
                ('correlation_tag', models.CharField(max_length=255)),
                ('manual_close', models.IntegerField()),
            ],
            options={
                'db_table': 'triggers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TriggerTag',
            fields=[
                ('triggertagid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('tag', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'trigger_tag',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('userid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('alias', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('passwd', models.CharField(max_length=32)),
                ('url', models.CharField(max_length=255)),
                ('autologin', models.IntegerField()),
                ('autologout', models.CharField(max_length=32)),
                ('lang', models.CharField(max_length=5)),
                ('refresh', models.CharField(max_length=32)),
                ('type', models.IntegerField()),
                ('theme', models.CharField(max_length=128)),
                ('attempt_failed', models.IntegerField()),
                ('attempt_ip', models.CharField(max_length=39)),
                ('attempt_clock', models.IntegerField()),
                ('rows_per_page', models.IntegerField()),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UsersGroups',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'users_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usrgrp',
            fields=[
                ('usrgrpid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('gui_access', models.IntegerField()),
                ('users_status', models.IntegerField()),
                ('debug_mode', models.IntegerField()),
            ],
            options={
                'db_table': 'usrgrp',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Valuemaps',
            fields=[
                ('valuemapid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'db_table': 'valuemaps',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Widget',
            fields=[
                ('widgetid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
            ],
            options={
                'db_table': 'widget',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WidgetField',
            fields=[
                ('widget_fieldid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('type', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('value_int', models.IntegerField()),
                ('value_str', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'widget_field',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CorrConditionGroup',
            fields=[
                ('corr_conditionid', models.OneToOneField(db_column='corr_conditionid', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='zabbix.CorrCondition')),
                ('operator', models.IntegerField()),
            ],
            options={
                'db_table': 'corr_condition_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CorrConditionTag',
            fields=[
                ('corr_conditionid', models.OneToOneField(db_column='corr_conditionid', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='zabbix.CorrCondition')),
                ('tag', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'corr_condition_tag',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CorrConditionTagpair',
            fields=[
                ('corr_conditionid', models.OneToOneField(db_column='corr_conditionid', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='zabbix.CorrCondition')),
                ('oldtag', models.CharField(max_length=255)),
                ('newtag', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'corr_condition_tagpair',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CorrConditionTagvalue',
            fields=[
                ('corr_conditionid', models.OneToOneField(db_column='corr_conditionid', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='zabbix.CorrCondition')),
                ('tag', models.CharField(max_length=255)),
                ('operator', models.IntegerField()),
                ('value', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'corr_condition_tagvalue',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EventRecovery',
            fields=[
                ('eventid', models.OneToOneField(db_column='eventid', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='zabbix.Events')),
                ('correlationid', models.BigIntegerField(blank=True, null=True)),
                ('userid', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'event_recovery',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GraphDiscovery',
            fields=[
                ('graphid', models.OneToOneField(db_column='graphid', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='discovery_graph', serialize=False, to='zabbix.Graphs')),
            ],
            options={
                'db_table': 'graph_discovery',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GroupDiscovery',
            fields=[
                ('groupid', models.OneToOneField(db_column='groupid', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='zabbix.Groups')),
                ('name', models.CharField(max_length=64)),
                ('lastcheck', models.IntegerField()),
                ('ts_delete', models.IntegerField()),
            ],
            options={
                'db_table': 'group_discovery',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HostDiscovery',
            fields=[
                ('hostid', models.OneToOneField(db_column='hostid', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='discovery_host', serialize=False, to='zabbix.Hosts')),
                ('host', models.CharField(max_length=64)),
                ('lastcheck', models.IntegerField()),
                ('ts_delete', models.IntegerField()),
            ],
            options={
                'db_table': 'host_discovery',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HostInventory',
            fields=[
                ('hostid', models.OneToOneField(db_column='hostid', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='zabbix.Hosts')),
                ('inventory_mode', models.IntegerField()),
                ('type', models.CharField(max_length=64)),
                ('type_full', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=64)),
                ('alias', models.CharField(max_length=64)),
                ('os', models.CharField(max_length=64)),
                ('os_full', models.CharField(max_length=255)),
                ('os_short', models.CharField(max_length=64)),
                ('serialno_a', models.CharField(max_length=64)),
                ('serialno_b', models.CharField(max_length=64)),
                ('tag', models.CharField(max_length=64)),
                ('asset_tag', models.CharField(max_length=64)),
                ('macaddress_a', models.CharField(max_length=64)),
                ('macaddress_b', models.CharField(max_length=64)),
                ('hardware', models.CharField(max_length=255)),
                ('hardware_full', models.TextField()),
                ('software', models.CharField(max_length=255)),
                ('software_full', models.TextField()),
                ('software_app_a', models.CharField(max_length=64)),
                ('software_app_b', models.CharField(max_length=64)),
                ('software_app_c', models.CharField(max_length=64)),
                ('software_app_d', models.CharField(max_length=64)),
                ('software_app_e', models.CharField(max_length=64)),
                ('contact', models.TextField()),
                ('location', models.TextField()),
                ('location_lat', models.CharField(max_length=16)),
                ('location_lon', models.CharField(max_length=16)),
                ('notes', models.TextField()),
                ('chassis', models.CharField(max_length=64)),
                ('model', models.CharField(max_length=64)),
                ('hw_arch', models.CharField(max_length=32)),
                ('vendor', models.CharField(max_length=64)),
                ('contract_number', models.CharField(max_length=64)),
                ('installer_name', models.CharField(max_length=64)),
                ('deployment_status', models.CharField(max_length=64)),
                ('url_a', models.CharField(max_length=255)),
                ('url_b', models.CharField(max_length=255)),
                ('url_c', models.CharField(max_length=255)),
                ('host_networks', models.TextField()),
                ('host_netmask', models.CharField(max_length=39)),
                ('host_router', models.CharField(max_length=39)),
                ('oob_ip', models.CharField(max_length=39)),
                ('oob_netmask', models.CharField(max_length=39)),
                ('oob_router', models.CharField(max_length=39)),
                ('date_hw_purchase', models.CharField(max_length=64)),
                ('date_hw_install', models.CharField(max_length=64)),
                ('date_hw_expiry', models.CharField(max_length=64)),
                ('date_hw_decomm', models.CharField(max_length=64)),
                ('site_address_a', models.CharField(max_length=128)),
                ('site_address_b', models.CharField(max_length=128)),
                ('site_address_c', models.CharField(max_length=128)),
                ('site_city', models.CharField(max_length=128)),
                ('site_state', models.CharField(max_length=64)),
                ('site_country', models.CharField(max_length=64)),
                ('site_zip', models.CharField(max_length=64)),
                ('site_rack', models.CharField(max_length=128)),
                ('site_notes', models.TextField()),
                ('poc_1_name', models.CharField(max_length=128)),
                ('poc_1_email', models.CharField(max_length=128)),
                ('poc_1_phone_a', models.CharField(max_length=64)),
                ('poc_1_phone_b', models.CharField(max_length=64)),
                ('poc_1_cell', models.CharField(max_length=64)),
                ('poc_1_screen', models.CharField(max_length=64)),
                ('poc_1_notes', models.TextField()),
                ('poc_2_name', models.CharField(max_length=128)),
                ('poc_2_email', models.CharField(max_length=128)),
                ('poc_2_phone_a', models.CharField(max_length=64)),
                ('poc_2_phone_b', models.CharField(max_length=64)),
                ('poc_2_cell', models.CharField(max_length=64)),
                ('poc_2_screen', models.CharField(max_length=64)),
                ('poc_2_notes', models.TextField()),
            ],
            options={
                'db_table': 'host_inventory',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InterfaceDiscovery',
            fields=[
                ('interfaceid', models.OneToOneField(db_column='interfaceid', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='interface', serialize=False, to='zabbix.Interface')),
            ],
            options={
                'db_table': 'interface_discovery',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Opcommand',
            fields=[
                ('operationid', models.OneToOneField(db_column='operationid', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='zabbix.Operations')),
                ('type', models.IntegerField()),
                ('execute_on', models.IntegerField()),
                ('port', models.CharField(max_length=64)),
                ('authtype', models.IntegerField()),
                ('username', models.CharField(max_length=64)),
                ('password', models.CharField(max_length=64)),
                ('publickey', models.CharField(max_length=64)),
                ('privatekey', models.CharField(max_length=64)),
                ('command', models.TextField()),
            ],
            options={
                'db_table': 'opcommand',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Opinventory',
            fields=[
                ('operationid', models.OneToOneField(db_column='operationid', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='zabbix.Operations')),
                ('inventory_mode', models.IntegerField()),
            ],
            options={
                'db_table': 'opinventory',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Opmessage',
            fields=[
                ('operationid', models.OneToOneField(db_column='operationid', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='zabbix.Operations')),
                ('default_msg', models.IntegerField()),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
            ],
            options={
                'db_table': 'opmessage',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('eventid', models.OneToOneField(db_column='eventid', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='problem_event', serialize=False, to='zabbix.Events')),
                ('source', models.IntegerField()),
                ('object', models.IntegerField()),
                ('objectid', models.BigIntegerField()),
                ('clock', models.IntegerField()),
                ('ns', models.IntegerField()),
                ('r_clock', models.IntegerField()),
                ('r_ns', models.IntegerField()),
                ('correlationid', models.BigIntegerField(blank=True, null=True)),
                ('userid', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'problem',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TaskAcknowledge',
            fields=[
                ('taskid', models.OneToOneField(db_column='taskid', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='zabbix.Task')),
                ('acknowledgeid', models.BigIntegerField()),
            ],
            options={
                'db_table': 'task_acknowledge',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TaskCloseProblem',
            fields=[
                ('taskid', models.OneToOneField(db_column='taskid', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='zabbix.Task')),
                ('acknowledgeid', models.BigIntegerField()),
            ],
            options={
                'db_table': 'task_close_problem',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TaskRemoteCommand',
            fields=[
                ('taskid', models.OneToOneField(db_column='taskid', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='zabbix.Task')),
                ('command_type', models.IntegerField()),
                ('execute_on', models.IntegerField()),
                ('port', models.IntegerField()),
                ('authtype', models.IntegerField()),
                ('username', models.CharField(max_length=64)),
                ('password', models.CharField(max_length=64)),
                ('publickey', models.CharField(max_length=64)),
                ('privatekey', models.CharField(max_length=64)),
                ('command', models.TextField()),
                ('alertid', models.BigIntegerField(blank=True, null=True)),
                ('parent_taskid', models.BigIntegerField()),
                ('hostid', models.BigIntegerField()),
            ],
            options={
                'db_table': 'task_remote_command',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TaskRemoteCommandResult',
            fields=[
                ('taskid', models.OneToOneField(db_column='taskid', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='zabbix.Task')),
                ('status', models.IntegerField()),
                ('parent_taskid', models.BigIntegerField()),
                ('info', models.TextField()),
            ],
            options={
                'db_table': 'task_remote_command_result',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TriggerDiscovery',
            fields=[
                ('triggerid', models.OneToOneField(db_column='triggerid', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='discovery_trigger', serialize=False, to='zabbix.Triggers')),
            ],
            options={
                'db_table': 'trigger_discovery',
                'managed': False,
            },
        ),
    ]
